#!/bin/sh
lock() {
    scrot /tmp/lock.png
    mogrify -scale 10% -scale 1000% /tmp/lock.png
    i3lock -u -i /tmp/lock.png
    rm /tmp/lock.png
}

case "$1" in
    lock)
        i3lock-fancy
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
